config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :products
  root 'products#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables
    has_many :products, through: :orderables

    def total
        orderables.to_a.sum { |orderable| orderable.total }
    end
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orderables
    has_many :carts, through: :orderables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_render_cart
    before_action :initialize_cart
  
    def set_render_cart
      @render_cart = true
    end
  
    def initialize_cart
      @cart ||= Cart.find_by(id: session[:cart_id])
  
      if @cart.nil?
        @cart = Cart.create
        session[:cart_id] = @cart.id
      end
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity:)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity:)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart',
                                                   partial: 'cart/cart',
                                                   locals: { cart: @cart }),
                              turbo_stream.replace(@product)]
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<html>
<head>
<style>
body {
    background-color: #93B874;
}
h1 {
    background-color: orange;
}
h2
{
  background-color: blue;
}

p {
    background-color: rgb(255,0,0);
}
</style>
</head>
<%= turbo_frame_tag "cart" do %>
  <h1>Cart</h1>
  <% if @cart.orderables.count > 0 %>
    <%= render "cart/orderables" %>
    <p>Total in Cart: <%= @cart.total %></p>
  <% else %>
    <h2>Your cart is empty</h2>
  <% end %>
<% end %>
</html>

app/views/cart/_orderables.html.erb
<% @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>
  <div id="<%= "cart-#{product.id}" %>">
    <div style="display:flex;justify-content:space-between;margin: 0em 5em;">
      <strong>Name:</strong>
      <%= product.name %>
      <strong>Description:</strong>
      <%= product.description %>
        <p>
    <strong>Image:</strong>
  
    <%= image_tag (product.image), alt: 'fun' %>
  </p> 
      <strong>Price:</strong>
      <%= product.price %>
      <%= form_with(url: cart_add_path) do |f| %>
        <%= f.hidden_field :id, value: product.id %>
        <%= f.number_field :quantity, value: orderable.quantity, min: 0 %>
        <%= f.submit "Update Cart" %>
      <% end %>
      <%= form_with(url: cart_remove_path) do |f| %>
        <%= f.hidden_field :id, value: orderable.id %>
        <%= f.submit "Delete this product from cart" %>
      <% end %>
      <strong>Total in this product:</strong>
      <%= orderable.total %>
    </div>
  </div>
<% end %>

app/views/cart/show.html.erb
<h1>YourCart</h1>
<% @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>
  <p><%= product.name %> * <%= orderable.quantity %> = $<%= product.price * orderable.quantity %></p>
<% end %>
<p>Your total is $<%= @cart.total %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CartProduct</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render partial: "cart/cart" if @render_cart %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div style="display:flex;justify-content:space-between;margin: 0em 5em;">
      
    <strong>Name:</strong>
    <%= product.name %>
      
      
      
    <strong>Description:</strong>
    <%= product.description %>
      
  <p>
    <strong>Image:</strong>
  
    <%= image_tag (product.image), alt: 'fun' %>
  </p> 
    
    <strong>Price:</strong>
    <%= product.price %>
      
        <p>
      
    <%= form_with(url: cart_add_path) do |f| %>
      <%= f.hidden_field :id, value: product.id %>
      <%= f.number_field :quantity, value: 0, min: 1 %>

       <% if @cart.orderables.map(&:product_id).include?(product.id)  %>
 
     <p>The product has been added to cart </p>
    
  
      <% else %>
      <%= f.submit "Add To Cart" %>
       <% end %>
    <% end %>
      </p>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Our Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

 <%# <%= link_to "New product", new_product_path %> 

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>